version: '3.9'

services:
  api:
    build: .
    container_name: api
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_USER=txemita
      - POSTGRES_PASSWORD=mi_contrase単a
      - POSTGRES_DB=txemita
      - MONGO_USER=josemariagodoy1996_db_user
      - MONGO_PASSWORD=micontrase単a1234
      - MONGO_DB=example
      - MONGO_URI=mongodb://mongo:27017/example
    depends_on:
      - postgres
      - mongo

  postgres:
    image: postgres:16
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: txemita
      POSTGRES_PASSWORD: mi_contrase単a
      POSTGRES_DB: txemita
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongo:
    image: mongo:7
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: josemariagodoy1996_db_user
      MONGO_INITDB_ROOT_PASSWORD: micontrase単a1234
    volumes:
      - mongodata:/data/db

volumes:
  pgdata:
  mongodata:
